config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show]
  resources :schedule_reviews, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :class_reviews, only: [:create, :update, :destroy]
  resources :courses, only: [:index, :show]
  get '/search/:search_term', to: 'class_reviews#search', as: 'search'
  post '/search', to: 'class_reviews#search_redirect', as: 'search_redirect'
end

app/controllers/schedule_reviews_controller.rb
class ScheduleReviewsController < ApplicationController
  before_action :set_schedule_review, only: [:show, :edit, :update, :destroy]

  # GET /schedule_reviews
  # GET /schedule_reviews.json
  def index
    @schedule_reviews = ScheduleReview.all
  end

  # GET /schedule_reviews/1
  # GET /schedule_reviews/1.json
  def show
  end

  # GET /schedule_reviews/new
  def new
    @schedule_review = ScheduleReview.new
    @class_review = ClassReview.new
  end

  # GET /schedule_reviews/1/edit
  def edit
  end

  # POST /schedule_reviews
  # POST /schedule_reviews.json
  def create
    @schedule_review = ScheduleReview.create( difficulty: params[:schedule_review][:difficulty], review: params[:schedule_review][:review], user: current_user)
    params[:schedule_review][:class_reviews_attributes].each do |num, class_rev|
      if not class_rev[:courses][:course_id].blank?
      ClassReview.create(difficulty: class_rev[:difficulty], workload: class_rev[:workload], professor: class_rev[:professor],
                         user: current_user, course: Course.find(class_rev[:courses][:course_id]), schedule_review: @schedule_review)
      end
    end
    puts @schedule_review.errors.full_messages.to_sentence
    if @schedule_review.errors.blank?
      redirect_to @schedule_review
    else
      flash[:error] = @schedule_review.errors.full_messages.to_sentence
      redirect_to new_schedule_review_path
    end
  end

  # PATCH/PUT /schedule_reviews/1
  # PATCH/PUT /schedule_reviews/1.json
  def update
    respond_to do |format|
      if @schedule_review.update(schedule_review_params)
        format.html { redirect_to @schedule_review, notice: 'Schedule review was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule_review }
      else
        format.html { render :edit }
        format.json { render json: @schedule_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_reviews/1
  # DELETE /schedule_reviews/1.json
  def destroy
    @schedule_review.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: 'Schedule review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def class_review_params
    params.require(:difficulty).permit(:professor, schedule_review_attributes[:id, :review])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule_review
      @schedule_review = ScheduleReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_review_params
      # params.fetch(:schedule_review, {})
      params.require(:schedule_review).permit(:user_id, :difficulty, :review)
    end
end

app/helpers/schedule_reviews_helper.rb
module ScheduleReviewsHelper
end

app/views/schedule_reviews/_form.html.erb
<%= form_for(setup_schedule_review(ScheduleReview.new)) do |f| %>
    <%= f.fields_for :class_reviews do |class_review| %>
        <%= class_review.fields_for :courses do |course| %>
            <%= course.label :name %>
            <%= course.collection_select :course_id, Course.order(:name),:id,:name, include_blank: true %> <br />
        <% end %>
        <%= class_review.label :professor %>
        <%= class_review.text_field :professor %> <br />
        <%= class_review.label :difficulty %>
        <%= class_review.number_field :difficulty, min: 0, max: 10 %> <br />
        <%= class_review.label :workload %>
        <%= class_review.number_field :workload, min: 0, max: 10 %> <br />

        <% if class_review.object.persisted? %>
            <%= class_review.check_box :_destroy %>
            <%= class_review.label :_destroy, "Delete" %>
        <% end %><br />
    <% end %>
    <%= f.label :difficulty, "Overall Difficulty" %>
    <%= f.number_field :difficulty, step: :any, min: 0.0, max: 10.0 %> <br />
    <%= f.label :review %> <br />
    <%= f.text_area :review, :cols => "120", :rows => "10" %> <br />
    <%= f.button :submit %> <br /> <br />
<% end %>

app/views/schedule_reviews/_schedule_review.html.erb
<div class="schedule_review">
  <% schedule_review.class_reviews.each do |class_rev| %>
    <%= render class_rev %>
  <% end %>

  <p class="rating">
    Overall Difficulty: <%= schedule_review.difficulty %>
  </p>
  Review: <%= schedule_review.review %><br/>

  <% if @user == current_user %>
    <tr>
      <td><%= link_to 'Edit', edit_schedule_review_path(schedule_review) %></td>
      <td><%= link_to 'Delete', schedule_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr><br/>
  <% end %>
</div>

app/views/schedule_reviews/edit.html.erb
<h1>Editing Schedule Review</h1>

<%= render 'form', schedule_review: @schedule_review %>

<%= link_to 'Show', @schedule_review %> |
<%= link_to 'Back', user_path(current_user.id) %>

app/views/schedule_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedule Reviews</h1>

<% @schedule_reviews = @schedule_reviews.sort {|r1,r2| r2 <=> r1} %>
<% @schedule_reviews.each do |schedule| %>
    <p class="schedule_name"><%= link_to schedule.user.name, schedule %></li>
    <ul class="schedule_list">
      <% schedule.class_reviews.each do |classrev| %>
      <li> <%= classrev.course.name %> </li>
      <% end %>
    </ul>
  <% end %>

app/views/schedule_reviews/new.html.erb
<h1>New Schedule Review</h1>

<%= render 'form', schedule_review: @schedule_review %>

app/views/schedule_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'schedule_review', schedule_review: @schedule_review %>

<% if @schedule_review.user == current_user %>
  <%= link_to 'Edit', edit_schedule_review_path(@schedule_review) %> |
  <%= link_to 'Delete', @schedule_review, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Back', user_path(current_user.id) %>
<% else %>
  <%= link_to 'View all of ' + @schedule_review.user.name + '\'s reviews', @schedule_review.user %>
<% end %>