config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show]
  resources :schedule_reviews, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :class_reviews, only: [:create, :update, :destroy]
  resources :courses, only: [:index, :show]
  get '/search/:search_term', to: 'class_reviews#search', as: 'search'
  post '/search', to: 'class_reviews#search_redirect', as: 'search_redirect'
end

app/controllers/class_reviews_controller.rb
class ClassReviewsController < ApplicationController
  before_action :set_class_review, only: [:show, :edit, :update, :destroy]

  # GET /class_reviews
  # GET /class_reviews.json
  def index
    @class_reviews = ClassReview.all
  end

  # GET /class_reviews/1
  # GET /class_reviews/1.json
  def show
  end

  # GET /class_reviews/new
  def new
    @class_review = ClassReview.new
    @course = Course.new
  end

  # GET /class_reviews/1/edit
  def edit
  end

  # POST /class_reviews
  # POST /class_reviews.json
  def create
    @class_review = ClassReview.new(class_review_params)

    respond_to do |format|
      if @class_review.save
        format.html { redirect_to @class_review, notice: 'Class review was successfully created.' }
        format.json { render :show, status: :created, location: @class_review }
      else
        format.html { render :new }
        format.json { render json: @class_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_reviews/1
  # PATCH/PUT /class_reviews/1.json
  def update
    respond_to do |format|
      if @class_review.update(class_review_params)
        format.html { redirect_to @class_review, notice: 'Class review was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_review }
      else
        format.html { render :edit }
        format.json { render json: @class_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_reviews/1
  # DELETE /class_reviews/1.json
  def destroy
    @class_review.destroy
    respond_to do |format|
      format.html { redirect_to class_reviews_url, notice: 'Class review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    search = params[:search_term]
    searches = search.split(/\s*,\s*/)
    @course_results = Set.new
    @schedule_results = Set.new
    searches.each do |term|
      courses = []
      has_course_number = search.count("0-9") > 0
      if has_course_number
        course_number = term[/\d+/]
        department = term.split(course_number).first.rstrip
        dept = Department.where('name like ?', '%'+department+'%')
        if dept.empty?
          dept = Department.where('abbreviation like ?', '%'+department+'%')
        end
        if not dept.empty?
          dept.each do |dep|
            course_number = term.split(department)[-1].strip
            courses = courses.concat(dep.courses.where('name like ?', '%'+course_number+'%'))
          end
        end
      else
        dept = Department.where('name like ?', '%'+term.strip+'%')
        if dept.empty?
          dept = Department.where('abbreviation like ?', '%'+term.strip+'%')
        end
        if not dept.empty?
          dept.each do |dep|
            courses = courses.concat(dep.courses)
          end
        end
      end
      @course_results.merge(courses.to_set)
    end
    @course_results.each do |course|
      reviews = course.class_reviews
      schedules = []
      reviews.each do |rev|
        schedules.append(rev.schedule_review)
      end
      @schedule_results.merge(schedules.to_set)
    end
  end

  def search_redirect
    puts 'foo'
    puts params
    redirect_to search_path(:search_term => params[:search_term])
  end

  def course_params
    params.require(:name).permit(:department_id, class_reviews_attributes: [:id, :difficulty, :workload, :professor])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_review
      @class_review = ClassReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_review_params
      params.fetch(:class_review, {})
    end
end

app/helpers/class_reviews_helper.rb
module ClassReviewsHelper
end

app/views/class_reviews/_class_review.html.erb
<!-- <%= render partial: "shared/class_review", locals: {class_review: class_review} %> -->

<div class="class_review">
  <p class="rating">
    <%= link_to class_review.course.name, course_path(class_review.course_id) %>
  </p>
  <p class="rating">
    Difficulty: <%= class_review.difficulty %>/10
  </p>
  <p class="rating">
    Workload: <%= class_review.workload %>/10
  </p>
  <p>
    Suggested prerequisite classes: <%= class_review.prereqs.to_sentence %>
  </p>
  <p>
    Professor: <%= class_review.professor %>
  </p>
</div>

app/views/class_reviews/_form.html.erb
<%= form_with(model: class_review, local: true) do |form| %>
  <% if class_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_review.errors.count, "error") %> prohibited this class_review from being saved:</h2>

      <ul>
      <% class_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_reviews/edit.html.erb
<h1>Editing Class Review</h1>

<%= render 'form', class_review: @class_review %>

<%= link_to 'Show', @class_review %> |
<%= link_to 'Back', class_reviews_path %>

app/views/class_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_reviews.each do |class_review| %>
      <tr>
        <td><%= link_to 'Show', class_review %></td>
        <td><%= link_to 'Edit', edit_class_review_path(class_review) %></td>
        <td><%= link_to 'Destroy', class_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class Review', new_class_review_path %>

app/views/class_reviews/new.html.erb
<h1>New Class Review</h1>

<%= render 'form', class_review: @class_review %>

<%= link_to 'Back', class_reviews_path %>

app/views/class_reviews/search.html.erb
<%= form_tag(search_redirect_path, method: "post") do %>
  <%= label_tag(:search_term, "Search for class(es):") %>
  <%= text_field_tag(:search_term) %>
  <%= submit_tag("Search") %>
<% end %>

<h2>Courses</h2>
<% if @course_results.empty? %>
	<p>No course results. </p>
<% else %>
	<% @course_results.each do |course| %>
		 <p class="course_name"><%= link_to course.name, course %></li>
	<% end %>
<% end %>

<h2>Schedules</h2>
<% if @schedule_results.empty? %>
	<p>No schedule results. </p>
<% else %>
  <% @schedule_results = @schedule_results.sort {|r1,r2| r2 <=> r1} %>
  <% @schedule_results.each do |schedule| %>
		<p class="schedule_name"><%= link_to schedule.user.name, schedule %></li>
		<ul class="schedule_list">
			<% schedule.class_reviews.each do |classrev| %>
			<li> <%= classrev.course.name %> </li>
			<% end %>
		</ul>
	<% end %>
<% end %>

app/views/class_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_class_review_path(@class_review) %> |
<%= link_to 'Back', class_reviews_path %>