config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show]
  resources :schedule_reviews, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :class_reviews, only: [:create, :update, :destroy]
  resources :courses, only: [:index, :show]
  get '/search/:search_term', to: 'class_reviews#search', as: 'search'
  post '/search', to: 'class_reviews#search_redirect', as: 'search_redirect'
end

app/views/layouts/_navbar.html.erb
 <header class="container-fluid" id="navbar">
        <div class="row">
            <a href="/" id="navlogo"><h1 class="col-sm-4">ScheduleReviewer</h1></a>
            <nav class="col-sm-6">
                <a href="/">
                    <p>home</p>
                </a>
                <a href="<%= new_schedule_review_path%>">
                    <p>submit review</p>
                </a>
                <a href="<%= courses_path %>">
                    <p>all classes</p>
                </a>
                <a href="<%= schedule_reviews_path %>">
                    <p>all schedule reviews</p>
                </a>
                <a href="<%= users_path %>">
                  <p>all users</p>
                </a>
            </nav>
        </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule Rater</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  </head>
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= link_to current_user.name, user_path(current_user.id) %></strong>.
    <%= link_to 'Home', root_path, :class=> 'navbar-link' %> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>

  <body>
    <div><%= render "layouts/navbar" %></div>
    <%= yield %>
  </body>
</html>